### PR TITLE
index.js is definitely correct ha ha

### PR DESCRIPTION
**Pull request by kevtrng**
fixed index.ejs so that groceries list is totally rendering ! @jsam07

### CODE REVIEW

**Comment by jsam07** [comment]
Hey @kevtrng , I'm still not able to see the list rendering, seems like Node is complaining because it doesn't have access to a `grocerieiseiesieisieiesies` list. Have another look at the code and push the relevant changes once you get it rendering properly. One more thing, be sure to use a `for/in` loop for iterating over the list items.

**Comment by kevtrng** [comment]
Hey @jsam07 ! I fixed it and you should be able to see the list rendering.

**Comment by jsam07** [comment]
🚀 Perfect, thanks @kevtrng!

**Comment by jsam07** [comment]
Closes #1.

**Pull request merged**
